naam = input("wat is uw naam? ")
#adres = input("wat is uw adres? ")
#postcode = input("wat is uw postcode? ")
#woonplaats= input("wat is uw woonplaats? ")

print ("----------------------------------------------------")
print ("|  Naam      : {naam}")
print (f"|  Adres     : {adres}")
print (f"|  Postcode  : {postcode}")
print (f"|  Woonplaats: {woonplaats}")
print ("----------------------------------------------------")